# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# ---- Builder Stage ----
FROM node:lts-alpine AS builder

# Install build dependencies for sharp
RUN apk add --no-cache python3 make g++ vips-dev fftw-dev

WORKDIR /app

# Copy package manifests
COPY package.json package-lock.json tsconfig.json ./
# Copy source
COPY src ./src

# Install dependencies (ignore scripts to avoid premature mcp-build)
RUN npm install --ignore-scripts && npm rebuild sharp

# Build the project
RUN npm run build

# ---- Runtime Stage ----
FROM node:lts-alpine

# Install runtime dependencies for sharp
RUN apk add --no-cache vips-dev fftw-dev

WORKDIR /app

# Copy built artifacts and node_modules
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules

# Default to dev mode; can be overridden via config
ENV MODE=dev

# Expose HTTP port if in prod
EXPOSE 1337

# Start the MCP server
CMD ["node", "dist/index.js"]
